Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), 
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path, include
from .views import add_to_cart, remove_from_cart, remove_single_item_from_cart, view_cart

app_name = 'cart'

urlpatterns = [
    path('order-summary/', view_cart, name='order-summary'),
    path('add-to-cart/<id>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<id>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<id>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
]

shop/urls.py
from django.urls import path, include
from .views import ItemDetailView, HomeView, search, cables, powerbanks, earphones

app_name = 'shop'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('product/<id>', ItemDetailView, name='product'),
    path('search/', search, name='search'),
    path('cables/', cables, name='cables'), 
    path('powerbanks/', powerbanks, name='powerbanks'),
    path('earphones/', earphones, name='earphones'),
]

shop/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.shortcuts import reverse

# Create your models here.

CATEGORY_CHOICES = (
    ('PC', 'Phone Cables'),
    ('PB', 'Power Banks'),
    ('EP', 'Earphone')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to='images/', null=True)

    def __str__(self):
        return self.title
        
    
    def get_absolute_url(self):
        return reverse("shop:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("cart:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("cart:remove-from-cart", kwargs={
            'slug': self.slug
        })
        

shop/views.py
from django.shortcuts import render
from shop.models import Item 
from checkout.models import OrderItem
from django.views.generic import ListView, DetailView, View
from django.db.models import Q
from django.shortcuts import get_object_or_404
# Create your views here.

def calculate_no_of_items(request):
    all_cart_items = OrderItem.objects.filter(user=request.user)
    count = 0
    for cart_item in all_cart_items:
        count += 1
    return count

def products(request):
    context = {
        'items': Item.objects.all()
    }
    return render(request, "product.html", context)
    
def ItemDetailView(request, id=None):
    item = get_object_or_404(Item, id=id)

    context = {
        "item": item
    }
    return render(request, "product.html", context)    
    
    
class HomeView(ListView):
    model = Item
    paginate_by = 50
    template_name = "home.html"
 

def cables(request):
    items = Item.objects.filter(category='PC')
    return render(request, "filter.html",  {'items': items})
    
def powerbanks(request):
    items = Item.objects.filter(category='PB')
    return render(request, "filter.html",  {'items': items})
    
def earphones(request):
    items = Item.objects.filter(category='EP')
    return render(request, "filter.html",  {'items': items})
    
    
def search(request):
    query = request.GET.get('q')
    products=Item.objects.filter(name__icontains=query)
    return render(request, "search.html", {'products': products, 'query':query})

shop/templates/filter.html
{% extends 'base.template.html' %} 
{% load static %}
{%block content %}

<!-- Hero Image -->
  <div class="d-none d-lg-block" id="hero-image">
    <img src="{% static 'images/main.png' %}" class="container-fluid px-0" alt="Responsive image">
  </div>
  
  <div class="d-lg-none" id="m-image">
    <img src="{% static 'images/m-main.png' %}" class="container-fluid px-0" alt="Responsive image">
  </div>

<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">All</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/cables">Phone Cables</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/powerbanks">Power Banks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/earphones">Earphones</a>
          </li>

        </ul>
        <!-- Links -->

        <form class="form-inline" method='GET'>
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name='q'>
            <input type='submit' value='Search'>
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <div class="row wow fadeIn">

        {% for item in items %}
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card">

            <div class="view overlay">
              {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %} <img src="{{ item.image.url }}" class="card-img-top">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
              </h5>

              <h4 class="font-weight-bold black-text">
                <strong>$
                  {{ item.price }}
                  <a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p mt-2">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
                  {% endif %}
                  </strong>
              </h4>

            </div>

          </div>

        </div>
        {% endfor %}
      </div>

    </section>


  </div>
</main>

{%endblock%}

shop/templates/home.html
{% extends 'base.template.html' %}
{% load static %}
{%block content %}

<!-- Hero Image -->
<div class="d-none d-lg-block" id="hero-image">
  <img src="{% static 'images/main.png' %}" class="container-fluid px-0">
</div>

<div class="d-lg-none" id="m-image">
  <img src="{% static 'images/m-main.png' %}" class="container-fluid px-0">
</div>

<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">All</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/cables">Phone Cables</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/powerbanks">Power Banks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/earphones">Earphones</a>
          </li>

        </ul>
        <!-- Links -->

        <form class="form-inline" method='GET'>
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name='q'>
            <input type='submit' value='Search'>
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-5 pb-5">

      <div class="row wow fadeIn">

        {% for item in object_list %}
        <div class="col-lg-3 col-md-6" style="margin-bottom:30px;">

          <div class="card">

            <div class="view overlay">
              {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %} <img src="{{ item.image.url }}" class="card-img-top">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="{{ item.get_absolute_url }}">
              <div class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </div>
              <h5>
                <strong>
                    <div class="dark-grey-text">{{ item.title }}
                    </div>
                  </strong>
              </h5>
              
              <h4 class="font-weight-bold black-text">
                <strong>$
                  {{ item.price }}
                  </a>
                  <a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p mt-2">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
                  </strong>
              </h4>

            </div>

          </div>

        </div>
        {% endfor %}
      </div>

    </section>


  </div>
</main>

{%endblock%}

shop/templates/product.html
{% extends "base.template.html" %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn mb-5">

        <!--Grid column-->
        <div class="col-md-6 mb-4 d-flex align-items-center justify-content-center">

          <img src="{{ item.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ item.get_category_display }}</span>
              </a>
            </div>
            
            <p class="lead font-weight-bold">{{ item.title }}</p>

            <p class="lead">
              <span>${{ item.price }}</span>
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ item.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ item.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->



      


    </div>
  </main>

{% endblock content %}

shop/templates/search.html
{% extends 'base.template.html' %} 
{% load static %}
{%block content %}

<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">All</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/cables">Phone Cables</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/powerbanks">Power Banks</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/earphones">Earphones</a>
          </li>

        </ul>
        <!-- Links -->

        <form class="form-inline" method='GET'>
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name='q'>
            <input type='submit' value='Search'>
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->


<section class="text-center mb-4">
  {% if products %}
      <h3>These are the results for your search '{{query}}':</h3>

      <div class="row wow fadeIn">

        {% for product in products %}
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card">

            <div class="view overlay">
              {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %} <img src="{{ item.image.url }}" class="card-img-top">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
              </h5>

              <h4 class="font-weight-bold black-text">
                <strong>$
                  {{ item.price }}
                  <a href="{{ item.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p mt-2">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
                  {% endif %}
                  </strong>
              </h4>

            </div>

          </div>

        </div>
        {% endfor %}
      </div>
{% endif %}
    </section>




{%endblock%}