Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static 
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')), 
    path('', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path, include
from .views import add_to_cart, remove_from_cart, remove_single_item_from_cart, view_cart

app_name = 'cart'

urlpatterns = [
    path('order-summary/', view_cart, name='order-summary'),
    path('add-to-cart/<id>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<id>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<id>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
]

cart/models.py
from django.db import models
from django.conf import settings
from shop.models import Item

# Create your models here.
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import View
from .models import OrderItem
from shop.models import Item
from django.utils import timezone

# Create your views here.



def calculate_cart_cost(request):
    all_cart_items = OrderItem.objects.filter(user=request.user)
    amount = 0
    for cart_item in all_cart_items:
        amount += cart_item.item.price * cart_item.quantity
        
    return amount

@login_required
def view_cart(request):
    amount = calculate_cart_cost(request)
    all_cart_items = OrderItem.objects.filter(user=request.user)
    return render(request, 'order_summary.html',{
            'all_cart_items':all_cart_items,
            'amount':amount
        })

@login_required
def add_to_cart(request, id):

    item = Item.objects.get(id=id)
    existing_cart_item = OrderItem.objects.filter(user=request.user, item=item).first()

    # if the cart item does not exist, create a new one
    if existing_cart_item == None:
        new_cart_item = OrderItem()
        new_cart_item.item = item
        new_cart_item.user = request.user
        new_cart_item.quantity = 1
        new_cart_item.save()
        messages.info(request, "This item quantity was updated.")
        return redirect("cart:order-summary")
    else:
        # increases its quantity
        existing_cart_item.quantity += 1
        existing_cart_item.save()
        messages.info(request, "This item was added to your cart.")
        return redirect("cart:order-summary")
        
        
@login_required
def remove_from_cart(request, id):
    
    item = Item.objects.get(id=id)
    existing_cart_item = OrderItem.objects.filter(user=request.user, item=item).first()
    existing_cart_item.delete()
    messages.info(request, "This item was removed from your cart.")
    return redirect("cart:order-summary")



@login_required
def remove_single_item_from_cart(request, id):
    
    item = Item.objects.get(id=id)
    existing_cart_item = OrderItem.objects.filter(user=request.user, item=item).first()

    if existing_cart_item != None:
        if existing_cart_item.quantity > 1:
            existing_cart_item.quantity -= 1
            existing_cart_item.save()
        else:
            existing_cart_item.delete()
        messages.info(request, "This item quantity was updated.")
        return redirect("cart:order-summary")
        

cart/templates/order_summary.html
{% extends "base.template.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in all_cart_items %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'cart:remove-single-item-from-cart' order_item.item.id %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'cart:add-to-cart' order_item.item.id %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
                ${{ order_item.get_total_item_price }}
            <a style='color: red;' href="{% url 'cart:remove-from-cart' order_item.item.id %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ amount }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}